name: Setup OIDC

on:
  workflow_call:
    inputs:
      aws_account_id:
        description: "AWS Account ID"
        required: true
        type: string
      aws_region:
        description: "AWS Region"
        required: true
        type: string
      role_name:
        description: "IAM Role name to create or update (usa diferente para permisos distintos)"
        required: true
        type: string
      repo_names:
        description: "Lista completa de repos autorizados (e.g., [\"repo1\",\"repo2\"]); pasa todos para evitar sobreescritura"
        required: true
        type: string
      actions:
        description: "Lista completa de acciones AWS permitidas (e.g., [\"ec2:*\",\"s3:*\"]); pasa todos para el rol"
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    outputs:
      role_arn:
        description: "ARN del IAM Role creado/actualizado"
        value: ${{ jobs.setup-oidc.outputs.github_role_arn }}
      oidc_provider_arn:
        description: "ARN del OIDC Provider"
        value: ${{ jobs.setup-oidc.outputs.oidc_provider_arn }}

jobs:
  setup-oidc:
    runs-on: ubuntu-latest
    outputs:
      github_role_arn: ${{ steps.tf-outputs.outputs.github_role_arn }}
      oidc_provider_arn: ${{ steps.tf-outputs.outputs.oidc_provider_arn }}

    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4

      - name: Checkout reusable workflows repo
        uses: actions/checkout@v4
        with:
          repository: pulidovpe/reusable-workflows
          ref: main
          path: reusable-workflows

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: |
          cd reusable-workflows/terraform/oidc
          terraform init -input=false

      - name: Terraform Apply
        run: |
          cd reusable-workflows/terraform/oidc
          terraform apply -auto-approve -input=false \
            -var 'aws_account_id=${{ inputs.aws_account_id }}' \
            -var 'aws_region=${{ inputs.aws_region }}' \
            -var 'role_name=${{ inputs.role_name }}' \
            -var 'repo_names=${{ inputs.repo_names }}' \
            -var 'actions=${{ inputs.actions }}'

      - name: Get Terraform Outputs
        id: tf-outputs
        run: |
          cd reusable-workflows/terraform/oidc
          echo "oidc_provider_arn=$(terraform output -raw oidc_provider_arn)" >> $GITHUB_OUTPUT
          echo "github_role_arn=$(terraform output -raw github_role_arn)" >> $GITHUB_OUTPUT