name: OIDC Setup

on:
  workflow_call:
    inputs:
      aws_account_id:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      role_name:
        required: true
        type: string
      repo_names:
        description: 'Repos autorizados. Ej: ["org/repo1","org/repo2"]'
        required: true
        type: string
      actions:
        description: 'Acciones dinámicas. Ej: ["ec2:*","s3:*"]'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  setup-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform
        run: terraform init
        working-directory: terraform/oidc

      - name: Apply Terraform
        run: terraform apply -auto-approve -input=false \
          -var="aws_account_id=${{ inputs.aws_account_id }}" \
          -var="aws_region=${{ inputs.aws_region }}" \
          -var="role_name=${{ inputs.role_name }}" \
          -var='repo_names=${{ inputs.repo_names }}' \
          -var='actions=${{ inputs.actions }}'
        working-directory: terraform/oidc
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.aws_region }}
